<a href="https://colab.research.google.com/github/ittus/learning-pytorch/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

## LISTS

In [4]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

## NUMPY ARRAYS

In [5]:
np1 = np.random.rand(3,4)
np1

array([[0.73439451, 0.5629718 , 0.18663052, 0.06863823],
       [0.95507593, 0.48372039, 0.70893053, 0.92611531],
       [0.33782346, 0.65666279, 0.58918537, 0.37304646]])

In [6]:
np1.dtype

dtype('float64')

## TENSORS

In [14]:
tensor_2d = torch.randn(3,4)
tensor_2d
# tensor_2d.dtype

tensor([[-0.0455, -1.2426,  0.7920, -1.4275],
        [ 0.5903,  1.2025,  0.1537,  0.6246],
        [ 0.1324,  0.1024,  0.5222, -0.9537]])

In [9]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

## Create tensor from numpy array

In [10]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.7344, 0.5630, 0.1866, 0.0686],
        [0.9551, 0.4837, 0.7089, 0.9261],
        [0.3378, 0.6567, 0.5892, 0.3730]], dtype=torch.float64)

# Tensor ops

In [16]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
# Reshape and view
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [21]:
# Reshape if we don't know the number of items using -1
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
my_torch2 = my_torch2.reshape(2, -1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [24]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [26]:
# Update & mutation
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
my_torch6 = my_torch5.reshape(2, 5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [28]:
my_torch5[1] = 123
my_torch5

tensor([  0, 123,   2,   3,   4,   5,   6,   7,   8,   9])

In [29]:
my_torch6

tensor([[  0, 123,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

In [30]:
# Slices
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
# Get an element
my_torch7[7]

tensor(7)

In [32]:
# get a slice
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [34]:
my_torch8[:, 1]

tensor([1, 3, 5, 7, 9])

In [37]:
# return columns
my_torch8[:, 1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

# TENSOR MATH OPERATIONS

In [38]:
tensor_a = torch.tensor([1, 2, 3, 4])
tensor_b = torch.tensor([5, 6, 7, 8])

In [39]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [40]:
# Addition longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [41]:
# Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [42]:
# sub function
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [43]:
# multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [44]:
# mul longhand
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [45]:
# division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [46]:
# div longhand
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [47]:
# Remainder Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [50]:
# Reminder longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [51]:
# Exponents / power
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [53]:
# Another way to write longhand
tensor_a.add(tensor_b)


tensor([ 6,  8, 10, 12])

In [55]:
# Reassignment
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [56]:
tensor_a

tensor([ 6,  8, 10, 12])